name: Node.js CI

on:
  push:
    branches:
      - '*'  # Runs on any branch
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  auto-pr-merge:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref != 'refs/heads/main'  # Only run on non-main branches
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config --global user.email "bharathsethuraman23@gmail.com"
          git config --global user.name "Bharath-Sethuraman"

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Create Pull Request to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git fetch origin main
            git branch -D temp-branch || true  # Delete existing branch if it exists
            git checkout -b temp-branch
            git add .
            git commit -m "Auto commit to create PR"
            git push origin temp-branch --force
            gh pr create --base main --head temp-branch --title "Auto PR to main" --body "This is an automated PR to the main branch."
          else
            echo "No changes detected. Skipping PR creation."
          fi
