name: Auto Create and Merge PR to Main

on:
  push:
    branches:
      - '**'  # Trigger for all branches

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-create-and-merge-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Check if the branch is `main`
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "Running on main, skipping PR creation."
            exit 0
          fi

      - name: Create Pull Request to Main
        id: create-pr
        run: |
          PR_NUMBER=$(gh pr create --base main --head "${GITHUB_REF#refs/heads/}" --title "Auto PR from ${GITHUB_REF#refs/heads/}" --body "This is an automated PR." --assignee @me --json number -q ".number")
          echo "Created PR #$PR_NUMBER"
          echo "::set-output name=pr_number::$PR_NUMBER"

      - name: Merge PR
        run: |
          PR_NUMBER="${{ steps.create-pr.outputs.pr_number }}"
          echo "Merging PR #$PR_NUMBER into main..."
          gh pr merge "$PR_NUMBER" --merge --auto
