name: Node.js CI

on:
  push:
    branches: 
      - '*'  # Trigger for pushes to any branch (including branches other than main)
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  auto-pr-merge:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref != 'refs/heads/main'  # Only run on non-main branches
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure Git user identity
      - name: Set up Git identity
        run: |
          git config --global user.email "bharathsethuraman23@gmail.com"  # Replace with your email
          git config --global user.name "Bharath-Sethuraman"  # Replace with your name

      # Create PR to main branch using GitHub CLI
      - name: Create Pull Request to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b temp-branch
          git add .
          git commit -m "Auto commit to create PR"
          git push origin temp-branch
          gh pr create --base main --head temp-branch --title "Auto PR to main" --body "This is an automated PR to the main branch."
