name: Node.js CI

on:
  push:
    branches: 
      - '*'  # Trigger for pushes to any branch (including branches other than main)
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  create-pr:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref != 'refs/heads/main'  # Only run on non-main branches
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config --local user.email "bharathsethuraman23@gmail.com"  # Replace with your email
          git config --local user.name "Bharath-Sethuraman"  # Replace with your name
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
      - name: Create Pull Request to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          gh pr create --base main --head "$CURRENT_BRANCH" --title "Auto PR to main" --body "This is an automated PR to the main branch."