name: Auto Pull Request to Main

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-commit: Update from ${{ github.ref_name }}"
          title: "Auto PR: Update from ${{ github.ref_name }}"
          body: "This is an automated pull request created from ${{ github.ref_name }}."
          base: main  # Target branch for the PR
          branch: auto-pr-${{ github.ref_name }}  # Creates a temp branch
          delete-branch: true  # Deletes temp branch after merging
          draft: false  # Change to true for draft PRs
          labels: auto-pr  # Optional: Adds label

      - name: Output PR URL
        run: echo "Pull Request URL ${{ steps.create-pr.outputs.pull-request-url }}"
