name: Node.js CI

on:
  push:
    branches:
      - "**" # Runs on any branch except main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr-merge:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config --global user.email "bharathsethuraman23@gmail.com"
          git config --global user.name "Bharath-Sethuraman"

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Check for new commits
        id: check_commits
        run: |
          if [ -z "$(git log origin/main..HEAD --oneline)" ]; then
            echo "::set-output name=has_new_commits::false"
          else
            echo "::set-output name=has_new_commits::true"
          fi

      - name: Create Pull Request to main
        if: steps.check_commits.outputs.has_new_commits == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          gh pr create --base main --head "$CURRENT_BRANCH" --title "Auto PR to main" --body "This is an automated PR to the main branch."

  ci:
    runs-on: ubuntu-latest
    needs: auto-pr-merge
    if: needs.auto-pr-merge.outputs.has_new_commits == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build --if-present

      - name: Run tests
        run: npm test

  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: needs.ci.result == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Merge PR to main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          PR_NUMBER=$(gh pr list --base main --head "$CURRENT_BRANCH" --json number --jq '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            echo "Merging PR #$PR_NUMBER"
            gh pr merge "$PR_NUMBER" --merge --delete-branch
          else
            echo "No PR found for branch $CURRENT_BRANCH"
            exit 1
          fi

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          # Add your deployment script here (e.g., SSH, Heroku, AWS, etc.)
