name: Node.js CI

on:
  push:
    branches:
      - "**" # Runs on any branch except main

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  auto-pr:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Check if PR already exists
        id: check-pr
        run: |
          PR_NUMBER=$(gh pr list --base main --head "$BRANCH_NAME" --json number --jq '.[0].number' || echo "")
          if [ -z "$PR_NUMBER" ]; then
            echo "No existing PR found for branch $BRANCH_NAME."
          else
            echo "Existing PR number: $PR_NUMBER"
          fi
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update PR
        if: env.PR_NUMBER == ''
        run: |
          echo "Creating a new PR for branch $BRANCH_NAME"
          gh pr create --base main --head "$BRANCH_NAME" --title "Auto PR: $BRANCH_NAME" --body "This is an auto-created PR."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update existing PR
        if: env.PR_NUMBER != ''
        run: |
          echo "Updating existing PR: $PR_NUMBER"
          gh pr comment "$PR_NUMBER" --body "New changes pushed to branch $BRANCH_NAME."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}