name: Node.js CI

on:
  push:
    branches:
      - "**" # Runs on any branch except main

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-pr-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Check if PR already exists
        id: check-pr
        run: |
          PR_NUMBER=$(gh pr list --base main --head "$BRANCH_NAME" --json number --jq '.[0].number' || echo "")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update PR
        if: env.PR_NUMBER == ''
        run: |
          gh pr create --base main --head "$BRANCH_NAME" --title "Auto PR: $BRANCH_NAME" --body "This is an auto-created PR."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for PR approval
        if: env.PR_NUMBER != ''
        run: |
          echo "Waiting for PR approval before merging..."
          gh pr review "$PR_NUMBER" --approve
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ensure All Checks Passed
        if: env.PR_NUMBER != ''
        run: |
          echo "Waiting for all checks to pass before merging..."
          # Check if status checks have passed
          gh pr checks "$PR_NUMBER" --status=success
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        if: env.PR_NUMBER != ''
        run: |
          echo "Merging PR $PR_NUMBER..."
          gh pr merge "$PR_NUMBER" --squash --delete-branch --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
