name: Node.js CI

on:
  push:
    branches: 
      - '*'  # Trigger for pushes to any branch (excluding main)
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  create-pr:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref != 'refs/heads/main'  # Only run on non-main branches

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git identity
        run: |
          git config --local user.email "bharathsethuraman23@gmail.com"
          git config --local user.name "Bharath-Sethuraman"

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh
          
      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token

      - name: Create or Update Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          
          # Check if a PR already exists
          PR_EXISTS=$(gh pr list --base main --head "$CURRENT_BRANCH" --json number --jq '.[0].number')

          if [ -z "$PR_EXISTS" ]; then
            echo "No existing PR found. Creating a new one..."
            gh pr create --base main --head "$CURRENT_BRANCH" --title "Auto PR to main" --body "This is an automated PR to the main branch."
          else
            echo "A PR for branch '$CURRENT_BRANCH' already exists: https://github.com/${{ github.repository }}/pull/$PR_EXISTS"
            echo "Pushing new changes to update the existing PR..."
            git push origin "$CURRENT_BRANCH"
          fi
