name: Node.js CI

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-pr-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get open PRs targeting main
        id: list-prs
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/Bharath-Sethuraman/checkCiCd/pulls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Auto-Merge for PRs
        if: ${{ steps.list-prs.outputs.data != '[]' }}
        run: |
          echo '${{ steps.list-prs.outputs.data }}' | jq -c '.[] | select(.base.ref=="main")' | while read -r pr; do
            pr_number=$(echo "$pr" | jq -r '.number')
            mergeable=$(echo "$pr" | jq -r '.mergeable')
            if [ "$mergeable" == "true" ]; then
              echo "Enabling Auto-Merge for PR #$pr_number..."
              gh pr merge $pr_number --auto --merge
            else
              echo "⚠️ PR #$pr_number has conflicts. Cannot enable auto-merge."
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
