name: Auto PR & Merge with CI/CD

on:
  push:
    branches:
      - "**" # Runs on any branch except main

permissions:
  contents: write
  pull-requests: write
  actions: write  # To allow actions to perform CI/CD steps

jobs:
  auto-pr-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Check if PR already exists
        id: check-pr
        run: |
          PR_NUMBER=$(gh pr list --base main --head "$BRANCH_NAME" --json number --jq '.[0].number' || echo "")
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update PR
        if: env.PR_NUMBER == ''
        run: |
          gh pr create --base main --head "$BRANCH_NAME" --title "Auto PR: $BRANCH_NAME" --body "This is an auto-created PR."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update existing PR
        if: env.PR_NUMBER != ''
        run: |
          gh pr comment "$PR_NUMBER" --body "New changes pushed to branch $BRANCH_NAME."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable Auto-Merge
        run: gh pr merge --auto --squash "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ci:
    runs-on: ubuntu-latest
    needs: auto-pr-merge # Ensure this runs after PR is created

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build --if-present

      - name: Run tests
        run: npm test

  cd:
    runs-on: ubuntu-latest
    needs: ci # Ensure this runs after CI job passes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to production (or staging)
        run: |
          echo "Deploying to production..."
          # Add your deployment script here (e.g., SSH, Heroku, AWS, etc.)
