name: Auto Merge PRs to Main

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-pr-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get open PRs targeting main
        id: list-prs
        run: |
          PR_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                          https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=main)
          # Ensure the PR_DATA is passed in one line format for environment variable
          echo "PR_LIST=$PR_DATA" >> $GITHUB_ENV

      - name: Debug PR Data (Raw)
        run: |
          echo "Raw PR List: $PR_LIST"

      - name: Enable Auto-Merge for PRs
        if: ${{ steps.list-prs.outputs.PR_LIST != '[]' }}
        run: |
          echo "$PR_LIST" | jq -c '.[]' | while read -r pr; do
            pr_number=$(echo "$pr" | jq -r '.number')
            echo "Enabling Auto-Merge for PR #$pr_number..."
            curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -d '{"merge_method": "merge"}' \
                 "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/merge"
          done

      - name: Merge PRs
        if: ${{ steps.list-prs.outputs.PR_LIST != '[]' }}
        run: |
          echo "$PR_LIST" | jq -c '.[]' | while read -r pr; do
            pr_number=$(echo "$pr" | jq -r '.number')
            echo "Merging PR #$pr_number into main..."
            curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -d '{"merge_method": "merge"}' \
                 "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/merge"
          done
