name: Auto Pull Request to Main

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-commit: Update from ${{ github.ref }}"
          title: "Auto PR: Update from ${{ github.ref }}"
          body: "This is an automated pull request created from ${{ github.ref }}."
          base: main  # Target branch for the PR
          branch: auto-pr-${{ github.ref }}  # Temporary branch for the PR
          delete-branch: true  # Delete the temporary branch after merging
          draft: false  # Set to true if you want to create a draft PR
          labels: auto-pr  # Optional: Add a label to the PR

      - name: Output PR URL
        run: echo "Pull Request URL:${{ steps.create-pr.outputs.pull-request-url }}"